language: java
sudo: false

os:
  - linux
  
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

before_install:
  - which mvn
  - mvn --version
  - export M3_HOME="/usr/local/maven"

install:
  - make test
