language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

before_install:
  - mvn --version
  - export M3_HOME="/usr/local/maven"
  - export JP_TRAVIS="true"
  - export JP_VERBOSE="true"
