language: java

os:
  - linux
  
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7

before_install:
  - export M3_HOME="/usr/local/maven"

script:
  - make build-no-test
  - sudo make install
  - mvn test
